### ISSUE TITLE
class/id naming

### ISSUE THREAD

**Issue by Karyum** [facn2/week1-717FAC#12]
https://github.com/facn2/week1-717FAC/blob/master/index.html#L19

you should use kebab case or camel case or snake case ...  to make the class names or id or var or whatever more readable :maple_leaf:

**Comment by veredrec** [comment]
@Karyum thanks for the comment. We changed all names to kebab-case.

**Comment by Karyum** [comment]
@veredrec GREAT JOB you guys also remmember to delete remote branches !!!
